application: cmweiss
version: 1
runtime: python
api_version: 1

handlers:
- url: /(.*\.svg)
  mime_type: image/svg+xml
  static_files: \1
  upload: (.*\.svg)

- url: /templateHTML
  static_dir: templateHTML

- url: /geomagJS
  static_dir: geomagJS

- url: /test
  static_dir: test

- url: /experiments
  static_dir: experiments

- url: /.*
  script: main.py
#   script: gae.py
