application: cmweiss
version: 1
runtime: python
api_version: 1

handlers:
- url: /templateHTML
  static_dir: templateHTML

- url: /geomagJS
  static_dir: geomagJS

- url: /test
  static_dir: test

- url: /experiments
  static_dir: experiments

- url: /(.*\.(svg))
  static_dir: /
  mime_type: image/svg+xml

- url: .*
  script: main.py
